### ISSUE TITLE
IOS Build Failed Undefined symbols for architecture x86_64:   "___isPlatformVersionAtLeast", referenced from:       -[PTFWInitialSetupHandler 

### ISSUE THREAD

**Issue by SABRYX** [paytabscom/react-native-paytabs-library#1]

**Comment by cogtea** [comment]
@SABRYX Can you please try the sample?

**Comment by cogtea** [comment]
@SABRYX Please mention the Xcode version?

I am able to run the example successfully without any issue, using Xcode `Version 11.3.1 (11C504)`

**Comment by cogtea** [comment]
@SABRYX I checked your issue, and built new beta release for IOS SDK to allow old Xcode versions to be built.

Please replace **paytabs-iOS.framework** (we mentioned here  https://github.com/paytabscom/react-native-paytabs-library#ios-1) in your project with attached one.

[paytabs-iOS.framework.zip](https://github.com/paytabscom/react-native-paytabs-library/files/4148466/paytabs-iOS.framework.zip)

**Comment by SABRYX** [comment]
@cogtea I'm sorry the new framework produces the same issue

**Comment by cogtea** [comment]
@SABRYX We built the IOS SDK with Xcode version 10.1, it should compile with old Xcode versions.

Please replace paytabs-iOS.framework (we mentioned here https://github.com/paytabscom/react-native-paytabs-library#ios-1) in your project with attached one.


[paytabs-iOS.framework.zip](https://github.com/paytabscom/react-native-paytabs-library/files/4163810/paytabs-iOS.framework.zip)

**Comment by SABRYX** [comment]
Did you make a new version?

**Comment by cogtea** [comment]
@SABRYX No need for new version, just replace **paytabs-iOs.framework**

**Comment by SABRYX** [comment]
I'm going to test it and tell you thanks :)

**Comment by SABRYX** [comment]
It's working perfectly now thanls for the support guys

**Comment by Zakyyy** [comment]
@SABRYX it is still showing the same error after I added the new framework
how did you solve it?
