### ISSUE TITLE
react-native-paytabs-library - Not found

### ISSUE THREAD

**Issue by josyvoxtron** [paytabscom/react-native-paytabs-library#11]
when i try to install 

npm install @paytabscom/react-native-paytabs-library@1.1.0-beta 
or 
npm install @paytabscom/react-native-paytabs-library@1.0.8 --save 

am getting following error
`D:\TesingProjects\reacttest\paytabtest>npm install @paytabscom/react-native-paytabs-library@1.0.8 --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@paytabscom%2freact-native-paytabs-library - Not found
npm ERR! 404
npm ERR! 404  '@paytabscom/react-native-paytabs-library@1.0.8' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-11-03T13_08_38_730Z-debug.log

D:\TesingProjects\reacttest\paytabtest>npm install @paytabscom/react-native-paytabs-library@1.1.0-beta
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@paytabscom%2freact-native-paytabs-library - Not found
npm ERR! 404
npm ERR! 404  '@paytabscom/react-native-paytabs-library@1.1.0-beta' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-11-03T13_08_57_570Z-debug.log

D:\TesingProjects\reacttest\paytabtest>` 
![image](https://user-images.githubusercontent.com/71818732/97990095-6e5a1800-1e05-11eb-9a3f-85da24c8f4e4.png)

**Comment by hexllhexll** [comment]
my to

**Comment by OsamaHarby** [comment]
me too

**Comment by Prinkal151** [comment]
same here

**Comment by ben-wiz** [comment]
Follow steps mentioned in https://github.com/paytabscom/react-native-paytabs-library/issues/2#issuecomment-593888588
And install using the command
`npm install react-native-paytabs-emulator@1.2.2 --save`

**Comment by michelazzam** [comment]
@ben-wiz  the solution didn't work for me

**Comment by icemaker** [comment]
@AdlyPayTabs can you help with the above error? how to solve it? @ben-wiz suggestion didnt work for me neither!

**Comment by fouadSalkini** [comment]
@AdlyPayTabs  +1

**Comment by michelazzam** [comment]
@ben-wiz In order to be able to install the package, on top of your solution I had to add couple of lines.

```
@paytabscom:registry=https://npm.pkg.github.com
@{{OWNER}}:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken={{TOKEN}}
```

In this case the owner will be: AdlyPayTabs >>` @AdlyPayTabs:registry=https://npm.pkg.github.com`

And to generate a personal token, navigate in your GitHub account to: 
- Settings > Developer settings > Personal access tokens 
- Generate new token
- From the permissions select at least read:packages
- Click Generate token and copy the token

**Comment by josyvoxtron** [comment]
Thank you @michelazzam it works
