### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by akshaykatale99** [paytabscom/react-native-paytabs-library#19]
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve cards.pay:paycardsrecognizer:1.1.0.
     Required by:
         project :app > project :paytabs_react-native-paytabs > com.paytabs:payment-sdk:6.0.6
      > Could not resolve cards.pay:paycardsrecognizer:1.1.0.
         > Could not get resource 'https://dl.bintray.com/paytabsandroidsdk/paytabs-sdk/cards/pay/paycardsrecognizer/1.1.0/paycardsrecognizer-1.1.0.pom'.
            > Could not HEAD 'https://dl.bintray.com/paytabsandroidsdk/paytabs-sdk/cards/pay/paycardsrecognizer/1.1.0/paycardsrecognizer-1.1.0.pom'. Received status code 403 from server: Forbidden

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gradle1256542939579254758.bin offset 176761 exists? true

**Comment by priyanshuvayuz** [comment]
Any update regarding this issue? @akshaykatale99 are you able to solve this issue

**Comment by rohitrvayuz** [comment]
@paytabscom @MuhamedAdly @mohamedkhairy953 Any updates here?

**Comment by mohamedkhairy953** [comment]
Please update to 2.3.4

**Comment by priyanshuvayuz** [comment]
not able to fetch from http://pay.cards/maven @mohamedkhairy953 , that is why getting error this error.

**Comment by priyanshuvayuz** [comment]
Its working fine when only paytabs sdk integrated throughout the app but causing this error when already we have some sdk of others already present, please look into this issue @mohamedkhairy953 @MuhamedAdly @paytabscom

**Comment by mohamedkhairy953** [comment]
Please update to 6.1.9

**Comment by rohitrvayuz** [comment]
> Please update to 6.1.9
> […](#)

@mohamedkhairy953  The latest available version is 2.3.4

**Comment by taimoornaj** [comment]
I'm facing this isse please help "Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'."
