### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by arhmnsh** [paytabscom/react-native-paytabs-library#2]
Hi guys!
I'm getting this error when running `npm install`
<img width="779" alt="image" src="https://user-images.githubusercontent.com/1363724/73421496-24ed1180-4337-11ea-8a64-9306efb7bf17.png">

<details>
<summary>Logs ↓</summary>
<p>

```sh
Rahamans-MacBook-Pro:DailyJob AbdulRahaman$ npm install @paytabscom/react-native-paytabs-library@1.0.6 --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@paytabscom%2freact-native-paytabs-library - Not found
npm ERR! 404
npm ERR! 404  '@paytabscom/react-native-paytabs-library@1.0.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AbdulRahaman/.npm/_logs/2020-01-30T05_02_28_010Z-debug.log
\```

**Comment by cogtea** [comment]
@arhmnsh please check following:

> You need an access token to publish, install, and delete packages in GitHub Packages. You can use a personal access token to authenticate with your username directly to GitHub Packages or the GitHub API. You can use a GITHUB_TOKEN to authenticate using a GitHub Actions workflow.



https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages#authenticating-to-github-packages

**Comment by arhmnsh** [comment]
Hi @cogtea,
I think there is a misunderstanding. I'm not trying to publish my package, I'm trying to use your package by following the instructions in readme,

**Comment by cogtea** [comment]
@arhmnsh Please make sure you add https://github.com/paytabscom/react-native-paytabs-library/blob/master/example/.npmrc#L1 to your project


https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages#installing-a-package

**Comment by AhmedHF** [comment]
@arhmnsh 
1- create an .npmrc file to include a line specifying GitHub Packages URL and the account owner,
 and write this line in it
 "registry=https://npm.pkg.github.com/paytabscom"
2- go https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line to generate Personal access tokens
use it to logging in to npm 
$ npm login --registry=https://npm.pkg.github.com
> Username: USERNAME  
> Password: TOKEN  // from step 2
> Email: PUBLIC-EMAIL-ADDRESS
3- install package
