### ISSUE TITLE
Content type - application/json error

### ISSUE THREAD

**Issue by muskanjain16** [paytabscom/react-native-paytabs-library#20]
![Screenshot from 2021-07-16 10-48-23](https://user-images.githubusercontent.com/67887702/125937515-129b26f3-120a-494c-a921-a085ed511ee9.png)

When I click on pay now it gives an error :
Request must be in json format with content type application/json

**Comment by mr-engin3er** [comment]
Same issue.
I tried to downgrade the version also but nothing works for me.

**Comment by muskanjain16** [comment]
Resolved above issue with correct server key & client key and test with testing cards.
working fine now.

**Comment by technicalbirdVayuz** [comment]
How did you solve this issue? Does anything need to be done while passing parameters?
