### ISSUE TITLE
Payment Error

### ISSUE THREAD

**Issue by priyanshuvayuz** [paytabscom/react-native-paytabs-library#21]
When I do payment with test card , it shows me the "authentication failed! Check authentication header" error? I have used all creds as mentioned in doc in configuration. @MuhamedAdly @mohamedkhairy953 @paytabscom

**Comment by mohamedkhairy953** [comment]
Please Make sure you are using the correct server key, client key, currency and merchant country code

**Comment by technicalbirdVayuz** [comment]
Validated the mentioned keys, 

Getting this error, Request must be in JSON format with content-type Application/JSON.

**Comment by mohamedkhairy953** [comment]
There are keys for the web and keys for the mobile sdk.
You need to use the mobile sdk ones.
After using the correct keys, make sure you are passing valid currency and
merchant country code.
If you're sure that you pass all right, send the issue to
***@***.*** along with your passed data.

**Comment by randaomar** [comment]
There is nothing in documentation that mentions how to get the server key and the client key!! please explain how to get those keys! @mohamedkhairy953
